name: "Hassio Java Add-on (Development)"
version: "0.0.0"
slug: "hassio-java-addon"
description: "Home Assistant Add-on to allow Java interactions"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  8080/tcp: 8080
options:
  access_token: ""
schema:
  access_token: password